export const PARTY_TYPES = {
  SUPPLIER: "SUPPLIER",
  BUYER: "BUYER",
  BOTH: "BOTH",
};

export const INTAKE_STATUS = {
  PENDING: "PENDING",
  SOLD: "SOLD",
  CLEARED: "CLEARED",
  CANCELLED: "CANCELLED",
};

export const UNIT_CATEGORIES = {
  WEIGHT: "WEIGHT",
  LIQUID: "LIQUID",
  QUANTITY: "QUANTITY",
};
