
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
  Snapshot: 'Snapshot'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  password: 'password',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PartyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phoneNumber: 'phoneNumber',
  address: 'address',
  notes: 'notes',
  partyType: 'partyType',
  isActive: 'isActive',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  primaryUnit: 'primaryUnit',
  unitConversion: 'unitConversion',
  quantity: 'quantity',
  isActive: 'isActive',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IntakeTransactionScalarFieldEnum = {
  id: 'id',
  intakeNumber: 'intakeNumber',
  entryDate: 'entryDate',
  partyId: 'partyId',
  productId: 'productId',
  bagCount: 'bagCount',
  rate: 'rate',
  rateUnit: 'rateUnit',
  grossWeight: 'grossWeight',
  unit: 'unit',
  normalizedWeight: 'normalizedWeight',
  Bardana: 'Bardana',
  Khot: 'Khot',
  netWeight: 'netWeight',
  remainingWeight: 'remainingWeight',
  notes: 'notes',
  status: 'status',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IntakeAdvanceScalarFieldEnum = {
  id: 'id',
  intakeTransactionId: 'intakeTransactionId',
  partyId: 'partyId',
  amount: 'amount',
  notes: 'notes',
  supplierInvoiceId: 'supplierInvoiceId',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SaleTransactionScalarFieldEnum = {
  id: 'id',
  saleNumber: 'saleNumber',
  entryDate: 'entryDate',
  partyId: 'partyId',
  totalWeight: 'totalWeight',
  baseAmount: 'baseAmount',
  totalAdjustments: 'totalAdjustments',
  finalAmount: 'finalAmount',
  status: 'status',
  paidAmount: 'paidAmount',
  paymentStatus: 'paymentStatus',
  notes: 'notes',
  isDeleted: 'isDeleted',
  changeLog: 'changeLog',
  previousState: 'previousState',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SaleItemScalarFieldEnum = {
  id: 'id',
  saleId: 'saleId',
  productId: 'productId',
  weight: 'weight',
  unit: 'unit',
  normalizedWeight: 'normalizedWeight',
  rate: 'rate',
  rateUnit: 'rateUnit',
  amount: 'amount',
  userId: 'userId',
  businessId: 'businessId'
};

exports.Prisma.SalesTrackScalarFieldEnum = {
  id: 'id',
  saleTransactionId: 'saleTransactionId',
  saleItemId: 'saleItemId',
  intakeTransactionId: 'intakeTransactionId',
  supplierPartyId: 'supplierPartyId',
  buyerPartyId: 'buyerPartyId',
  productId: 'productId',
  quantity: 'quantity',
  buyingRate: 'buyingRate',
  sellingRate: 'sellingRate',
  rateUnit: 'rateUnit',
  netWeight: 'netWeight',
  baseAmount: 'baseAmount',
  isBilled: 'isBilled',
  isSettled: 'isSettled',
  notes: 'notes',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TransactionAdjustmentScalarFieldEnum = {
  id: 'id',
  saleId: 'saleId',
  adjustmentType: 'adjustmentType',
  method: 'method',
  value: 'value',
  calculatedAmount: 'calculatedAmount',
  direction: 'direction',
  unit: 'unit',
  userId: 'userId',
  businessId: 'businessId'
};

exports.Prisma.SupplierInvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  partyId: 'partyId',
  entryDate: 'entryDate',
  totalGrossValue: 'totalGrossValue',
  totalDeductions: 'totalDeductions',
  totalAdvances: 'totalAdvances',
  finalPayableAmount: 'finalPayableAmount',
  status: 'status',
  paidAmount: 'paidAmount',
  paymentStatus: 'paymentStatus',
  isOutdated: 'isOutdated',
  version: 'version',
  lastCalculatedAt: 'lastCalculatedAt',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierInvoiceAdjustmentScalarFieldEnum = {
  id: 'id',
  supplierInvoiceItemId: 'supplierInvoiceItemId',
  adjustmentType: 'adjustmentType',
  method: 'method',
  value: 'value',
  calculatedAmount: 'calculatedAmount',
  direction: 'direction',
  unit: 'unit',
  userId: 'userId',
  businessId: 'businessId'
};

exports.Prisma.SupplierInvoiceItemScalarFieldEnum = {
  id: 'id',
  supplierInvoiceId: 'supplierInvoiceId',
  intakeTransactionId: 'intakeTransactionId',
  weight: 'weight',
  rate: 'rate',
  amount: 'amount',
  userId: 'userId',
  businessId: 'businessId'
};

exports.Prisma.LedgerSessionScalarFieldEnum = {
  id: 'id',
  title: 'title',
  startDate: 'startDate',
  endDate: 'endDate',
  supplierTotal: 'supplierTotal',
  buyerTotal: 'buyerTotal',
  difference: 'difference',
  supplierInvoiceCount: 'supplierInvoiceCount',
  buyerInvoiceCount: 'buyerInvoiceCount',
  status: 'status',
  notes: 'notes',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductRateScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  rate: 'rate',
  unit: 'unit',
  date: 'date',
  source: 'source',
  isDeleted: 'isDeleted',
  notes: 'notes',
  createdBy: 'createdBy',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  entityType: 'entityType',
  entityId: 'entityId',
  action: 'action',
  description: 'description',
  userId: 'userId',
  userName: 'userName',
  businessId: 'businessId',
  meta: 'meta',
  createdAt: 'createdAt'
};

exports.Prisma.PartyPaymentScalarFieldEnum = {
  id: 'id',
  partyId: 'partyId',
  paymentNumber: 'paymentNumber',
  paymentType: 'paymentType',
  paymentMethod: 'paymentMethod',
  amount: 'amount',
  sourceType: 'sourceType',
  sourceId: 'sourceId',
  status: 'status',
  entryDate: 'entryDate',
  notes: 'notes',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PartyPaymentAllocationScalarFieldEnum = {
  id: 'id',
  partyId: 'partyId',
  paymentId: 'paymentId',
  referenceType: 'referenceType',
  referenceId: 'referenceId',
  allocatedAmount: 'allocatedAmount',
  userId: 'userId',
  businessId: 'businessId',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Party: 'Party',
  Product: 'Product',
  IntakeTransaction: 'IntakeTransaction',
  IntakeAdvance: 'IntakeAdvance',
  SaleTransaction: 'SaleTransaction',
  SaleItem: 'SaleItem',
  SalesTrack: 'SalesTrack',
  TransactionAdjustment: 'TransactionAdjustment',
  SupplierInvoice: 'SupplierInvoice',
  SupplierInvoiceAdjustment: 'SupplierInvoiceAdjustment',
  SupplierInvoiceItem: 'SupplierInvoiceItem',
  LedgerSession: 'LedgerSession',
  ProductRate: 'ProductRate',
  ActivityLog: 'ActivityLog',
  PartyPayment: 'PartyPayment',
  PartyPaymentAllocation: 'PartyPaymentAllocation'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
